"""Skill Fabricator — Detects missing tools/skills and auto-generates them.

Integrates with the existing skill system at ~/.claude/skills/
and auto-creates new skills when gaps are detected.
"""
import json
import os
import re
import sys
import time
import traceback
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, List, Optional, Set, Tuple

SKILLS_DIR = Path.home() / ".claude" / "skills"
FABRICATION_LOG = Path("/home/sahiix/sahiix-agi/data/fabrication_log.json")
MIN_REPETITION_TO_FABRICATE = 3  # same gap must hit 3x
COOLDOWN_HOURS = 24.0


class SkillFabricator:
    """Monitors agent behavior, detects recurring tool/skill gaps, fabricates new skills."""

    def __init__(self):
        self._gap_counter: Dict[str, int] = defaultdict(int)
        self._fabricated: Set[str] = set()
        self._log: List[Dict[str, Any]] = self._load_log()

    def _load_log(self) -> List[Dict[str, Any]]:
        if FABRICATION_LOG.exists():
            try:
                return json.loads(FABRICATION_LOG.read_text())
            except Exception:
                pass
        return []

    def _save_log(self):
        try:
            FABRICATION_LOG.parent.mkdir(parents=True, exist_ok=True)
            FABRICATION_LOG.write_text(json.dumps(self._log[-200:], indent=2))
        except Exception:
            pass

    # ── Gap Detection ──────────────────────────────────────────────────────

    def record_gap(self, tool_name: str, context: Optional[str] = None) -> bool:
        """Called when a tool/skill is missing. Returns True if fabrication triggered."""
        self._gap_counter[tool_name] += 1
        count = self._gap_counter[tool_name]

        # Log every gap
        self._log.append({
            "t": time.time(),
            "type": "gap_recorded",
            "tool": tool_name,
            "count": count,
            "context": context,
        })

        if count >= MIN_REPETITION_TO_FABRICATE:
            if self._can_fabricate(tool_name):
                self._fabricate_skill(tool_name, context)
                return True
        return False

    def _can_fabricate(self, tool_name: str) -> bool:
        recent = [e for e in self._log[-50:] if e.get("type") == "fabrication" and e.get("tool") == tool_name]
        if not recent:
            return True
        last_fab = max(e["t"] for e in recent)
        return (time.time() - last_fab) > (COOLDOWN_HOURS * 3600)

    # ── Actual Fabrication ─────────────────────────────────────────────────

    def _fabricate_skill(self, tool_name: str, context: Optional[str] = None):
        """Create a new skill directory with scaffold content."""
        skill_path = SKILLS_DIR / self._slug(tool_name)
        skill_path.mkdir(parents=True, exist_ok=True)

        # SKILL.md
        skill_md = skill_path / "SKILL.md"
        if not skill_md.exists():
            skill_md.write_text(self._skill_template(tool_name, context))

        # Metadata
        meta = skill_path / "skill.json"
        meta.write_text(json.dumps({
            "name": tool_name,
            "version": "1.0.0",
            "fabricated": datetime.now(timezone.utc).isoformat(),
            "context": context,
            "trigger": "auto_fabricated",
            "status": "draft",
        }, indent=2))

        self._log.append({
            "t": time.time(),
            "type": "fabrication",
            "tool": tool_name,
            "path": str(skill_path),
        })
        self._save_log()

    def _slug(self, name: str) -> str:
        return re.sub(r'[^a-zA-Z0-9_-]', '-', name).lower().strip('-')

    def _skill_template(self, tool_name: str, context: Optional[str]) -> str:
        return f"""# Skill: {tool_name}

## Description
Auto-fabricated skill to address a recurring gap: the system repeatedly needed
the ability to `{tool_name}` but no skill existed.

## Context
{context or "Detected automatically via gap analysis."}

## Usage

### When to Use
- When the task involves `{tool_name}` and no existing tool covers it.

### Steps
1. Analyze the requirement carefully.
2. Implement the functionality using available tools.
3. Test and verify.

## Example
```
# User: {tool_name} the output
# Action: [implement using best available tools]
```

## Notes
- This skill was auto-generated by the Skill Fabricator.
- Review and refine before production use.
- Consider promoting to a formal skill by adding to your skills registry.

---
*Fabricated: {datetime.now(timezone.utc).isoformat()}*
"""

    # ── Public API ─────────────────────────────────────────────────────────

    def status(self) -> Dict[str, Any]:
        return {
            "gaps_recorded": dict(self._gap_counter),
            "fabricated_count": len([e for e in self._log if e.get("type") == "fabrication"]),
            "recent_log": self._log[-20:],
            "skills_dir": str(SKILLS_DIR),
        }

    def list_fabricated(self) -> List[str]:
        return [e["tool"] for e in self._log if e.get("type") == "fabrication"]
